/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ukk_sppgita;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class form_siswa extends javax.swing.JFrame {
    Connection con;
    DefaultTableModel tm;
    String nisn;
    
    public void connect(){
        con=null;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_sppgita","root","");
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
    }
    
    public void refreshTable(){
        tm=new DefaultTableModel(null, new Object[] {"Nisn", "Nis", "Nama", "Kelas", "Alamat", "No Telp", "Tarif SPP"});
        jTable1.setModel(tm);
        tm.getDataVector().removeAllElements();
        try{
            PreparedStatement s = con.prepareStatement("SELECT siswa.nisn, siswa.nis, siswa.nama, kelas.nama_kelas, "
            + "siswa.alamat, siswa.no_telp, spp.nominal FROM siswa INNER JOIN kelas USING(id_kelas) INNER JOIN "
            + " spp using(id_spp)");
            ResultSet r = s.executeQuery();
            while(r.next()){
                Object[] data={
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7)
                };
                tm.addRow(data);
                }
            }catch (Exception e){
                System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
    }
    private void ambilData(){
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM spp");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
                tarif.addItem(r.getString("nominal"));
               
            }
        }catch(Exception e){
    }
    }
    
    private void Data(){
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM kelas");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
                nmkls.addItem(r.getString("nama_kelas"));
               
            }
        }catch(Exception e){
        }
    }
    
    /**
     * Creates new form form_siswa1
     */
    public form_siswa() {
        initComponents();
        connect();
        refreshTable();
        ambilData();
        Data();
        idkelas.hide();
        idspp.hide();

                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        notlpn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nmkls = new javax.swing.JComboBox<>();
        tarif = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cbnisn = new javax.swing.JTextField();
        idspp = new javax.swing.JTextField();
        idkelas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nisn");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 58, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nis");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 29, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 58, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Kelas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 58, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Telp");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 53, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tarif SPP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 58, -1));
        jPanel1.add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 360, 30));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 360, 30));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 360, 30));
        jPanel1.add(notlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 360, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-insert-35.png"))); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 120, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-available-updates-35.png"))); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 120, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-trash-35.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 120, 40));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-emergency-exit-35.png"))); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 120, 40));

        nmkls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Kelas" }));
        nmkls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmklsActionPerformed(evt);
            }
        });
        nmkls.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nmklsKeyPressed(evt);
            }
        });
        jPanel1.add(nmkls, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 280, 30));

        tarif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tarif" }));
        tarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarifMouseClicked(evt);
            }
        });
        tarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifActionPerformed(evt);
            }
        });
        tarif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tarifKeyPressed(evt);
            }
        });
        jPanel1.add(tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 280, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 690, 220));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-classroom-30.png"))); // NOI18N
        jLabel8.setText("FORM SISWA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        cbnisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnisnActionPerformed(evt);
            }
        });
        jPanel1.add(cbnisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 360, 30));

        idspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsppActionPerformed(evt);
            }
        });
        jPanel1.add(idspp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 60, 30));

        idkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idkelasActionPerformed(evt);
            }
        });
        jPanel1.add(idkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 60, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bk22.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cbnisn.getText().equals("") || nis.getText().equals("") ||  nama.getText().equals("") || idkelas.getText().equals("")  || alamat.getText().equals("")  || notlpn.getText().equals("") || idspp.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Data harus terisi semua");
        }else{
        try{
            PreparedStatement ps = con.prepareStatement("INSERT INTO siswa VALUES(?,?,?,?,?,?,?)");
            ps.setString(1, cbnisn.getText());
            ps.setString(2, nis.getText());
            ps.setString(3, nama.getText());
            ps.setString(4, idkelas.getText());
            ps.setString(5, alamat.getText());
            ps.setString(6, notlpn.getText());
            ps.setString(7, idspp.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data telah tersimpan");
            refreshTable();
        }catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Menghapus Siswa='"+
                nama.getText()+"'",".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
        if (ok==0){
        try{
            PreparedStatement ps = con.prepareStatement("DELETE FROM siswa WHERE nisn=?");
            ps.setString(1, cbnisn.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data telah dihapus");
            refreshTable();
        }catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        menu m=new menu();
        m.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        cbnisn.setText(tm.getValueAt(jTable1.getSelectedRow(),0).toString());
        nis.setText(tm.getValueAt(jTable1.getSelectedRow(),1).toString());
        nama.setText(tm.getValueAt(jTable1.getSelectedRow(),2).toString());
        idkelas.setText(tm.getValueAt(jTable1.getSelectedRow(),3).toString());
        alamat.setText(tm.getValueAt(jTable1.getSelectedRow(),4).toString());
        notlpn.setText(tm.getValueAt(jTable1.getSelectedRow(),5).toString());
        idspp.setText(tm.getValueAt(jTable1.getSelectedRow(),6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void nmklsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmklsActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM kelas where nama_kelas='"+
                    nmkls.getSelectedItem().toString() +"'");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
                idkelas.setText(r.getString("id_kelas"));
            }
        }catch(Exception e) {
        }
    }//GEN-LAST:event_nmklsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (cbnisn.getText().equals("") || nis.getText().equals("") ||  nama.getText().equals("") || idkelas.getText().equals("")  || alamat.getText().equals("")  || notlpn.getText().equals("") || idspp.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Data harus terisi semua");
        }else{
        try{
            PreparedStatement ps = con.prepareStatement("UPDATE siswa SET nis=?, nama=?, id_kelas=?, alamat=?, no_telp=?, id_spp=? WHERE nisn=?");
            ps.setString(1, nis.getText());
            ps.setString(2, nama.getText());
            ps.setString(3, idkelas.getText());
            ps.setString(4, alamat.getText());
            ps.setString(5, notlpn.getText());
            ps.setString(6, idspp.getText());
            ps.setString(7, cbnisn.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data telah diubah");
            refreshTable();
        }catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbnisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnisnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnisnActionPerformed

    private void nmklsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmklsKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nmklsKeyPressed

    private void tarifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tarifKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifKeyPressed

    private void idkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idkelasActionPerformed

    private void tarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM spp where nominal='"+
                    tarif.getSelectedItem().toString() +"'");
            ResultSet r = s.executeQuery();
            
            while (r.next()) {
                idspp.setText(r.getString("id_spp"));
            }
        }catch(Exception e) {
        }
    }//GEN-LAST:event_tarifActionPerformed

    private void idsppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsppActionPerformed

    private void tarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarifMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField cbnisn;
    private javax.swing.JTextField idkelas;
    private javax.swing.JTextField idspp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JComboBox<String> nmkls;
    private javax.swing.JTextField notlpn;
    private javax.swing.JComboBox<String> tarif;
    // End of variables declaration//GEN-END:variables
}
