/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ukk_sppgita;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class form_kelas extends javax.swing.JFrame {
    Connection con;
    DefaultTableModel tm;
    String idkelas;
    
    public void connect(){
        con=null;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_sppgita","root","");
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
    }
    
    public void refreshTable(){
        tm=new DefaultTableModel(null, new Object[] {"No", "Nama Kelas", "Kompetensi Keahlian"});
        tblkelas.setModel(tm);
        tblkelas.removeColumn(tblkelas.getColumnModel().getColumn(0));
        tm.getDataVector().removeAllElements();
        try{
            PreparedStatement s = con.prepareStatement("SELECT * FROM kelas");
            ResultSet r = s.executeQuery();
            while(r.next()){
                Object[] data={
                    r.getString(1),
                    r.getString(2),
                    r.getString(3)
                };
                tm.addRow(data);
                }
            }catch (Exception e){
                System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
    }
    
   
    /**
     * Creates new form form_siswa
     */
    public form_kelas() {
        initComponents();
        connect();
        refreshTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkelas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        cbcari = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbnmkelas = new javax.swing.JTextField();
        komkeahlian = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(206, 202, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Kelas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kompetensi Keahlian");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        tblkelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkelas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 689, 204));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-insert-35.png"))); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 132, 45));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-available-updates-35.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 138, 45));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-trash-35.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 148, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-emergency-exit-35.png"))); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 127, 45));
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 350, 31));

        cbcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-search-client-35 (1).png"))); // NOI18N
        cbcari.setText("Cari");
        cbcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcariActionPerformed(evt);
            }
        });
        jPanel1.add(cbcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 113, 31));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kelas.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 120, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM KELAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-rotate-right-35.png"))); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 110, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cari kelas By Nama Kelas  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        cbnmkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnmkelasActionPerformed(evt);
            }
        });
        jPanel1.add(cbnmkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 290, 30));
        jPanel1.add(komkeahlian, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 290, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bc.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcariActionPerformed
        // TODO add your handling code here:
        tm = new DefaultTableModel(null,
            new Object[] {"No", "Nama Kelas", "Kompetensi Keahlian" });
        tblkelas.setModel(tm);
        tblkelas.removeColumn(tblkelas.getColumnModel().getColumn(0));
        tm.getDataVector().removeAllElements();
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM kelas where id_kelas LIKE '%"+ txtcari.getText().toString()
                +"%' or nama_kelas LIKE '%"+ txtcari.getText().toString() +"%'");
            ResultSet r = ps.executeQuery();
            JOptionPane.showMessageDialog(this,"Data telah ditemukan");
            while(r.next()){
                Object[] data ={
                    r.getString(1),
                    r.getString(2),
                    r.getString(3)
                    
                };
                tm.addRow(data);
            }
        }catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
    }//GEN-LAST:event_cbcariActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        menu m=new menu();
        m.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Menghapus kelas='"+
                cbnmkelas.getText()+"'",".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
        if (ok==0){
        try{
            PreparedStatement ps = con.prepareStatement("DELETE FROM kelas WHERE id_kelas=?");
            ps.setString(1, idkelas);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data telah dihapus");
            refreshTable();
        }catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (cbnmkelas.getText().equals("") || komkeahlian.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Data harus terisi semua");
        }else{
        
        try{
            PreparedStatement ps = con.prepareStatement("UPDATE kelas SET nama_kelas=?, kompetensi_keahlian=? WHERE id_kelas='"+idkelas+"'");
            ps.setString(1, cbnmkelas.getText());
            ps.setString(2, komkeahlian.getText());
            ps.executeUpdate();
            refreshTable();
            
            JOptionPane.showMessageDialog(this,"Data telah diubah");
            refreshTable();
        }catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cbnmkelas.getText().equals("") || komkeahlian.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Data harus terisi semua");
        }else {
        
        try{
            PreparedStatement ps = con.prepareStatement("INSERT INTO kelas VALUES(?,?,?)");
            ps.setInt(1, 0);
            ps.setString(2, cbnmkelas.getText());
            ps.setString(3, komkeahlian.getText());
            ps.executeUpdate();
            refreshTable();
           
            JOptionPane.showMessageDialog(this,"Data telah tersimpan");
            refreshTable();
        }catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n "+e+"\n\n");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblkelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkelasMouseClicked
        // TODO add your handling code here:
        int i = tblkelas.getSelectedRow();
        if (i == -1){
            return;
        }
        
        String idkls = (String) tm.getValueAt(i, 0);
        idkelas=idkls;
        
        String nmkls = (String) tm.getValueAt(i, 1);
        cbnmkelas.setText(nmkls);
        
        String kom = (String) tm.getValueAt(i, 2);
        komkeahlian.setText(kom);
        
    }//GEN-LAST:event_tblkelasMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblkelas.getModel();
        model.setRowCount(0);
        refreshTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbnmkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnmkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnmkelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_kelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbcari;
    private javax.swing.JTextField cbnmkelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField komkeahlian;
    private javax.swing.JTable tblkelas;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}

